spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: Thanhtam2004.
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: sanbox.smtp.mailtrap.io
    port: 2525
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: sanbox.smtp.mailtrap.io
      mail.smtp.ssl.protocols: TLSv1.2
      mail.debug: true


jwt:
  secret: afe65bcd93be0f27d04415f68b9b6ca33f909553ad54c3966cd719a7e44606c1
  expiration: 86400000
  refresh-expiration: 604800000
server:
  port:  8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    csrf:
      enabled: true
      path: /swagger-ui.html
    openapi:
      service:
        api-docs: ecommerce
        title: Ecommerce Backend
        version: 1.0.0
      server: http://localhost:${server.port}